#!/bin/env bash

FRAKTUR_FONT_START=""
FRAKTUR_FONT_END=""
FRAKTUR_FONT_START="$(compgen -v)"
FRAKTUR_FONT_BORDER_DEFAULT="𝔸𝔹ℂ𝔻𝔼𝔽𝔾ℍ𝕀𝕁𝕂𝕃𝕄ℕ𝕆ℙℚℝ𝕊𝕋𝕌𝕍𝕎𝕏𝕐ℤ𝕒𝕓𝕔𝕕𝕖𝕗𝕘𝕙𝕚𝕛𝕜𝕝𝕞𝕟𝕠𝕡𝕢𝕣𝕤𝕥𝕦𝕧𝕨𝕩𝕪𝕫"
FRAKTUR_FONT_CESAR_DEFAULT="AMWOEZKFYBVXPQCGDLJRITNUHSbfnzuymvokwaecxjghrtqpisld"
FRAKTUR_FONT_CIRCLE_DEFAULT="ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ"
FRAKTUR_FONT_CIRCLE_BOLD="🅐🅑🅒🅓🅔🅕🅖🅗🅘🅙🅚🅛🅜🅝🅞🅟🅠🅡🅢🅣🅤🅥🅦🅧🅨🅩🅐🅑🅒🅓🅔🅕🅖🅗🅘🅙🅚🅛🅜🅝🅞🅟🅠🅡🅢🅣🅤🅥🅦🅧🅨🅩"
FRAKTUR_FONT_FRAKTUR_BOLD="𝕬𝕭𝕮𝕯𝕰𝕱𝕲𝕳𝕴𝕵𝕶𝕷𝕸𝕹𝕺𝕻𝕼𝕽𝕾𝕿𝖀𝖁𝖂𝖃𝖄𝖅𝖆𝖇𝖈𝖉𝖊𝖋𝖌𝖍𝖎𝖏𝖐𝖑𝖒𝖓𝖔𝖕𝖖𝖗𝖘𝖙𝖚𝖛𝖜𝖝𝖞𝖟"
FRAKTUR_FONT_FRAKTUR_DEFAULT="𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷"
FRAKTUR_FONT_ITALIC_DEFAULT="𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡𝘢𝘣𝘤𝘥𝘦𝘧𝘨𝘩𝘪𝘫𝘬𝘭𝘮𝘯𝘰𝘱𝘲𝘳𝘴𝘵𝘶𝘷𝘸𝘹𝘺𝘻"
FRAKTUR_FONT_RECT_DEFAULT="🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉"
FRAKTUR_FONT_RECT_BOLD="🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿🆀🆁🆂🆃🆄🆅🆆🆇🆈🆉🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿🆀🆁🆂🆃🆄🆅🆆🆇🆈🆉"
FRAKTUR_FONT_SCRIPT_DEFAULT="𝒜𝐵𝒞𝒟𝐸𝐹𝒢𝐻𝐼𝒥𝒦𝐿𝑀𝒩𝒪𝒫𝒬𝑅𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵𝒶𝒷𝒸𝒹𝑒𝒻𝑔𝒽𝒾𝒿𝓀𝓁𝓂𝓃𝑜𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏"
FRAKTUR_FONT_SCRIPT_BOLD="𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩𝓪𝓫𝓬𝓭𝓮𝓯𝓰𝓱𝓲𝓳𝓴𝓵𝓶𝓷𝓸𝓹𝓺𝓻𝓼𝓽𝓾𝓿𝓌𝓍𝓎𝓏"
FRAKTUR_FONT_END="$(compgen -v)"

FRAKTUR_FONTS=$(echo $FRAKTUR_FONT_START $FRAKTUR_FONT_END | tr ' ' '\n' | sort | uniq -u)

function fraktur_alphabet() {
	local FONT=$1
	shift
	local STYLE=$1
	shift
	
	printf FRAKTUR_FONT_%s_%s ${FONT} ${STYLE}
}

function fraktur_list_fonts() {
	local FONT
	for FONT in ${FRAKTUR_FONTS}; do
		local ALPHA=${!FONT}

		printf "%s: %s\n" "$(echo $FONT | cut -d '_' -f3-4 | sed 's/_/ /g')" "${ALPHA:0:10}"
	done
}

function fraktur_code() {
	printf '%d' "'$@'"
}

function fraktur() {
	local WORD=$1
	shift
	if [ -z "${WORD}" ]; then
		WORD="Hello World"
	fi

	local FONT=$1
	shift
	if [ -z "${FONT}" ]; then
		FONT=FRAKTUR
	fi

	local STYLE=$1
	shift
	if [ -z "${STYLE}" ]; then
		STYLE="DEFAULT"
	fi
	
	local ALPHA_FONT=$(fraktur_alphabet $FONT $STYLE)
	local ALPHA=${!ALPHA_FONT}
	if [ -z "${ALPHA}" ]; then
		echo 'Font "'$FONT'" not found :( Please use "fraktur_list_fonts" for all available fonts.' > /dev/stderr
		return -1
	fi

	local i=0
	for i in $(seq 0 ${#WORD}); do 
		local INDEX=0

		local c=${WORD:i:1}

		if [ $(fraktur_code $c) -ge $(fraktur_code "a") ] && [ $(fraktur_code $c) -le $(fraktur_code "z") ]; then 
			INDEX=$((26 + $(fraktur_code $c) - $(fraktur_code "a")))
		elif [ $(fraktur_code $c) -ge $(fraktur_code "A") ] && [ $(fraktur_code $c) -le $(fraktur_code "Z") ]; then
			INDEX=$(($(fraktur_code $c) - $(fraktur_code "A")))
		else
			echo -n "$c"
			continue
		fi

		if [ ! -z "${FRAKTUR_DEBUG}" ]; then
			echo "Index: $INDEX"
			echo "Font: $ALPHA_FONT"
		        echo "Alpha: $ALPHA"
		fi	       
	
		echo -n ${ALPHA:INDEX:1}
	done
}

