#!/bin/bash

function comedy_animal() {
	local YEAR=$1
	shift
	if [ -z "$YEAR" ]; then
                YEAR="$(curl --silent -X POST -d 'wrapAPIKey=7UF1tvyFxs4TXQDYq4btuIIfIuHvbSdz' https://wrapapi.com/use/mariobodemann/comedy-wildlife/list/0.0.1 | jq -r .[].url | sort --random-sort | head -1)"
        else
                YEAR="$(curl --silent -X POST -d 'wrapAPIKey=7UF1tvyFxs4TXQDYq4btuIIfIuHvbSdz' https://wrapapi.com/use/mariobodemann/comedy-wildlife/list/0.0.1 | jq -r .[].url | grep $YEAR| sort --random-sort | head -1)"
	fi

	local OUTPUT=/tmp/comedy_animal.jpg
	if [ ! -e /tmp ]; then
		OUTPUT="${HOME}/tmp/comedy"
		mkdir -p $OUTPUT
		OUTPUT="$OUTPUT/animal.jpg"
	fi

        local ANIMALS="$(curl --silent -X POST -H 'Content-Type: application/json' -d '{"year_link":"'$YEAR'", "wrapAPIKey":"7UF1tvyFxs4TXQDYq4btuIIfIuHvbSdz"}' https://wrapapi.com/use/mariobodemann/comedy-wildlife/year/0.0.5 | jq -r .[].url)"
        local ANIMAL_URL="$(echo $ANIMALS | grep -o '[^ ]*' | sort --random-sort | head -1)"
	echo $ANIMAL_URL
	curl --silent $ANIMAL_URL --output "$OUTPUT"

	if command -v chafa > /dev/null; then
		chafa --size 128x128 $OUTPUT
        else
		display "$OUTPUT"
	fi
}
