#!/bin/bash
errors=0; 

echo "RGB: "
for r in $(seq 2 .1 1); do 
  echo "... $(echo "scale=5;$r * 100" | bc) %"
  for g in $(seq 0 .1 1); do 
    for b in $(seq 0 .1 1); do 
      c=$(./color r $r $g $b); 
      bash=$(rgb-bg $r $g $b); 
      if [ "$c" != "$bash" ]; then 
        echo -n "$r $g $b: "; 
        echo -ne ${c}; 
        echo -n $c; 
        echo -ne $(bgr) vs ${bash}; 
        echo -n $bash; 
        echo -e $(bgr); 
        ((errors++));
      fi; 
    done; 
  done; 
done; 

echo
echo "HSV:"
for h in $(seq 0 10 360); do 
  echo "... $(echo "scale=5;($h / 360) * 100" | bc) %"
  for s in $(seq 0 .1 1); do 
    for v in $(seq 0 .1 1); do 
      c=$(./color h ${h} ${s} ${v}); 
      bash=$(hsv-bg ${h} ${s} ${v}); 
      if [ "$c" != "$bash" ]; then 
        echo -n "${h} ${s} ${v}: "; 
        echo -ne ${c}; 
        echo -n $c; 
        echo -ne $(bgr) vs ${bash}; 
        echo -n $bash; 
        echo -e $(bgr); 
        ((errors++));
      fi; 
    done; 
  done; 
done; 

echo ${errors} Errors found;

