#!/usr/bin/env python3

fonts = {
	'none':"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
	'border':"𝔸𝔹ℂ𝔻𝔼𝔽𝔾ℍ𝕀𝕁𝕂𝕃𝕄ℕ𝕆ℙℚℝ𝕊𝕋𝕌𝕍𝕎𝕏𝕐ℤ𝕒𝕓𝕔𝕕𝕖𝕗𝕘𝕙𝕚𝕛𝕜𝕝𝕞𝕟𝕠𝕡𝕢𝕣𝕤𝕥𝕦𝕧𝕨𝕩𝕪𝕫",
	'ceasar':"AMWOEZKFYBVXPQCGDLJRITNUHSbfnzuymvokwaecxjghrtqpisld",
	'circle':"ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ",
	'circle-bold':"🅐🅑🅒🅓🅔🅕🅖🅗🅘🅙🅚🅛🅜🅝🅞🅟🅠🅡🅢🅣🅤🅥🅦🅧🅨🅩🅐🅑🅒🅓🅔🅕🅖🅗🅘🅙🅚🅛🅜🅝🅞🅟🅠🅡🅢🅣🅤🅥🅦🅧🅨🅩",
	'fraktur-bold':"𝕬𝕭𝕮𝕯𝕰𝕱𝕲𝕳𝕴𝕵𝕶𝕷𝕸𝕹𝕺𝕻𝕼𝕽𝕾𝕿𝖀𝖁𝖂𝖃𝖄𝖅𝖆𝖇𝖈𝖉𝖊𝖋𝖌𝖍𝖎𝖏𝖐𝖑𝖒𝖓𝖔𝖕𝖖𝖗𝖘𝖙𝖚𝖛𝖜𝖝𝖞𝖟",
	'fraktur':"𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷",
	'italic':"𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡𝘢𝘣𝘤𝘥𝘦𝘧𝘨𝘩𝘪𝘫𝘬𝘭𝘮𝘯𝘰𝘱𝘲𝘳𝘴𝘵𝘶𝘷𝘸𝘹𝘺𝘻",
	'rect':"🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉",
	'rect-bold':"🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿🆀🆁🆂🆃🆄🆅🆆🆇🆈🆉🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿🆀🆁🆂🆃🆄🆅🆆🆇🆈🆉",
	'script':"𝒜𝐵𝒞𝒟𝐸𝐹𝒢𝐻𝐼𝒥𝒦𝐿𝑀𝒩𝒪𝒫𝒬𝑅𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵𝒶𝒷𝒸𝒹𝑒𝒻𝑔𝒽𝒾𝒿𝓀𝓁𝓂𝓃𝑜𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏",
	'script-bold':"𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩𝓪𝓫𝓬𝓭𝓮𝓯𝓰𝓱𝓲𝓳𝓴𝓵𝓶𝓷𝓸𝓹𝓺𝓻𝓼𝓽𝓾𝓿𝓌𝓍𝓎𝓏",
	'slack':[
		":alphabet-white-a:",
		":alphabet-white-b:",
		":alphabet-white-c:",
		":alphabet-white-d:",
		":alphabet-white-e:",
		":alphabet-white-f:",
		":alphabet-white-g:",
		":alphabet-white-h:",
		":alphabet-white-i:",
		":alphabet-white-j:",
		":alphabet-white-k:",
		":alphabet-white-l:",
		":alphabet-white-m:",
		":alphabet-white-n:",
		":alphabet-white-o:",
		":alphabet-white-p:",
		":alphabet-white-q:",
		":alphabet-white-r:",
		":alphabet-white-s:",
		":alphabet-white-t:",
		":alphabet-white-u:",
		":alphabet-white-v:",
		":alphabet-white-w:",
		":alphabet-white-x:",
		":alphabet-white-y:",
		":alphabet-white-z:",
		":alphabet-white-a:",
		":alphabet-white-b:",
		":alphabet-white-c:",
		":alphabet-white-d:",
		":alphabet-white-e:",
		":alphabet-white-f:",
		":alphabet-white-g:",
		":alphabet-white-h:",
		":alphabet-white-i:",
		":alphabet-white-j:",
		":alphabet-white-k:",
		":alphabet-white-l:",
		":alphabet-white-m:",
		":alphabet-white-n:",
		":alphabet-white-o:",
		":alphabet-white-p:",
		":alphabet-white-q:",
		":alphabet-white-r:",
		":alphabet-white-s:",
		":alphabet-white-t:",
		":alphabet-white-u:",
		":alphabet-white-v:",
		":alphabet-white-w:",
		":alphabet-white-x:",
		":alphabet-white-y:",
		":alphabet-white-z:",
	],
	'slack-yellow':[
		":alphabet-yellow-a:",
		":alphabet-yellow-b:",
		":alphabet-yellow-c:",
		":alphabet-yellow-d:",
		":alphabet-yellow-e:",
		":alphabet-yellow-f:",
		":alphabet-yellow-g:",
		":alphabet-yellow-h:",
		":alphabet-yellow-i:",
		":alphabet-yellow-j:",
		":alphabet-yellow-k:",
		":alphabet-yellow-l:",
		":alphabet-yellow-m:",
		":alphabet-yellow-n:",
		":alphabet-yellow-o:",
		":alphabet-yellow-p:",
		":alphabet-yellow-q:",
		":alphabet-yellow-r:",
		":alphabet-yellow-s:",
		":alphabet-yellow-t:",
		":alphabet-yellow-u:",
		":alphabet-yellow-v:",
		":alphabet-yellow-w:",
		":alphabet-yellow-x:",
		":alphabet-yellow-y:",
		":alphabet-yellow-z:",
		":alphabet-yellow-a:",
		":alphabet-yellow-b:",
		":alphabet-yellow-c:",
		":alphabet-yellow-d:",
		":alphabet-yellow-e:",
		":alphabet-yellow-f:",
		":alphabet-yellow-g:",
		":alphabet-yellow-h:",
		":alphabet-yellow-i:",
		":alphabet-yellow-j:",
		":alphabet-yellow-k:",
		":alphabet-yellow-l:",
		":alphabet-yellow-m:",
		":alphabet-yellow-n:",
		":alphabet-yellow-o:",
		":alphabet-yellow-p:",
		":alphabet-yellow-q:",
		":alphabet-yellow-r:",
		":alphabet-yellow-s:",
		":alphabet-yellow-t:",
		":alphabet-yellow-u:",
		":alphabet-yellow-v:",
		":alphabet-yellow-w:",
		":alphabet-yellow-x:",
		":alphabet-yellow-y:",
		":alphabet-yellow-z:",
	],
}


def fraktur(message='abcdefg ABCDEFG', font='fraktur'):
	out=''
	if font in fonts:
		for c in message:
			if c.isalpha():
				if c.isupper():
					index = ord(c) - ord('A')
				else:
					index = ord(c) - ord('a') + 26
	
				out += fonts[font][index]
			else:
				out += c
	return out

def fraktur_all(message='abcdefg ABCDEFG'):
	for font in fonts.keys():
		print('%s: %s' % (font, fraktur(message,font)))

import sys

if len(sys.argv) == 2:
	print(fraktur(sys.argv[1]))
elif len(sys.argv) == 3:
	if sys.argv[2] == 'all':
		fraktur_all(sys.argv[1])
	else:
		print(fraktur(sys.argv[1], sys.argv[2]))
else:
	print("Usage: %s MESSAGE FONT\n\nMESSAGE: Some text\nFONT: one of %s.\n" % (sys.argv[0], str(fonts.keys())))


