#!/bin/sh
#
# Shows graphical differences between assets. Needs ImageMagick.
#
# Please add a 
#
# > cat .gitattributes 
# *.gif diff=image
# *.jpg diff=image
# *.png diff=image
#
# and some
# 
# > git config --global core.attributesfile '~/.gitattributes'
# > git config --global diff.image.command '~/bin/git-imgdiff'
#

compare $2 $1 png:- | montage -background none -geometry +4+4 $2 - $1 png:- | display png:- -title "$1"
