#!/bin/bash

hash=$(git log --format=%h HEAD^..HEAD)
echo $hash

message="🦆👍🤓- $(git log --format=%s HEAD^..HEAD | tr '"' '-' | tr "'" "-")👨‍💻"
echo $message

if hash termux-camera-photo; then 
	mkdir -p /sdcard/Pictures/lols/
	picture_base="/sdcard/Pictures/lols"
	picture="${picture_base}/lol-$(date -Ins).jpg"
	termux-camera-photo -c 1 $picture
	output="${picture_base}/$(basename $picture .jpg)-final.jpg"
else 
	ffmpeg -i /dev/video0 /tmp/raw-lol-$(date -Ins)%03d.jpg -vframes 30
	picture="/tmp/lol*030.jpg"
	output=$picture
fi

convert \
	-background None \
	$picture \
	-resize 640x480 \
	\( \
		-gravity SouthWest \
		\( \
			-fill black \
			pango:"<tt>$message</tt>" \
			-morphology Edge disk:2 \
		\) \
		\( \
			-fill white \
			pango:"<tt>$message</tt>" \
		\) \
		-composite \
	\) \
	-composite \
	\( \
		-gravity NorthEast \
		\( \
			-fill black \
			pango:"<tt>$hash</tt>" \
			-morphology Edge disk:2 \
		\) \
		\( \
			-fill white \
			pango:"<tt>$hash</tt>" \
		\) \
		-composite \
	\) \
	-composite \
	$output

if hash termux-share; then 
	termux-share $output
else
	xdg-open $output
fi
