#!/bin/bash
DEBUG=1
function log() {
	if [ ${DEBUG} == 1 ]; then
		echo "$@"
	fi
}

RGB=$BASH_TOOLS_HOME/color
log Starting

IMAGE=$1
if [ -z "$IMAGE" ]; then 
	IMAGE="/usr/share/pixmaps/faces/legacy/sunset.jpg"
fi
log ${IMAGE}

SIZE="$(identify ${IMAGE} | cut -d' ' -f3)"
log $SIZE

WIDTH="$(echo ${SIZE} | cut -d 'x' -f1)"
log $WIDTH

log OUTPUTTING
X=0
RE="^([^,]+),([^,]+),(.*)$"

while read COLOR; do
	[[ "$COLOR" =~ $RE ]] && R="${BASH_REMATCH[1]}000" && G="${BASH_REMATCH[2]}000" && B="${BASH_REMATCH[3]}000"
	
	echo -ne "$($RGB r $(printf "%.3f %.3f %.3f" $((R / 255))e-3 $((G / 255))e-3 $((B / 255))e-3) ) "

	((X++))
	if [ "$X" -ge "$WIDTH" ]; then
		echo -e "\e[m"
		X=0
	fi
done <<< "$(convert ${IMAGE} txt: | grep -o 'srgb\(.*\)' | grep -o '[0-9]\+,[0-9]\+,[0-9]\+')"
echo

log DONE
