#!/data/data/com.termux/files/usr/bin/bash

source $HOME/.profile

TEXT=$(termux-dialog text -i 'to be encoded' -t 'What should be encoded?' | jq -r  .text)

qrencode -o /sdcard/Download/qr.code.png "${TEXT}"
termux-open /sdcard/Download/qr.code.png

toilet --gay --termwidth '<Done, ENTER to return>'
read
